USE swiggy;
SELECT * FROM restaurants;

-- RANK EVERY RESTAURANT FROM MOST EXPENSIVE TO LEAST EXPENSIVE
SELECT * ,RANK() OVER(ORDER BY cost DESC) AS "rank" FROM restaurants;

-- RANK EVERY RESTAURANTS FROM MOST VISITED TO LEAST VISITED
SELECT * ,RANK() OVER(ORDER BY rating_count DESC) AS "rank" FROM restaurants;

-- RANK EVERY RESTAURANT FROM MOST EXPENSIVE TO LEAST EXPENSIVE BASED ON THE CITY
SELECT * ,RANK() OVER( PARTITION BY city ORDER BY cost DESC) AS "rank" FROM restaurants ;

-- DENSE RANK EVERY RESTAURANT FROM MOST EXPENSIVE TO LEAST EXPENSIVE AS PER THEIR CITY
SELECT * ,DENSE_RANK() OVER( PARTITION BY city ORDER BY cost DESC) AS "dense_rank" FROM restaurants ;

SELECT * ,
RANK() OVER( PARTITION BY city ORDER BY cost DESC) AS "rank"  ,
DENSE_RANK() OVER( PARTITION BY city ORDER BY cost DESC) AS "dense_rank" FROM restaurants ;

-- ROW NUMBER EVERY RESTAURANT FROM MOST EXPENSIVE TO LEAST EXPENSIVE AS PER THEIR CITY
SELECT * ,ROW_NUMBER() OVER( PARTITION BY city ORDER BY cost DESC) AS "row_rank" FROM restaurants ;


SELECT * ,
RANK() OVER( PARTITION BY city ORDER BY cost DESC) AS "rank"  ,
DENSE_RANK() OVER( PARTITION BY city ORDER BY cost DESC) AS "dense_rank",
ROW_NUMBER() OVER( PARTITION BY city ORDER BY cost DESC) AS "row_rank" FROM restaurants ;

-- RANK EVERY RESTAURANTS FROM MOST EXPENSIVE TO LEAST EXPENSIVE AS PER THEIR CITY ALONG WITH ITS CITY (ADILABAD-1,ADILABAD-2)
SELECT *, ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost DESC) AS "rank" FROM restaurants;

SELECT *, CONCAT(city ,"-",ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost DESC)) AS "rank" FROM restaurants;

-- FIND THE TOP 5 restaurants of every city as per their revenue


SELECT *,cost*rating_count AS "revenue",ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost*rating_count DESC) AS "rank" FROM restaurants;


SELECT * FROM
 (SELECT *,cost*rating_count AS "revenue",ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost*rating_count DESC) AS "rank" FROM restaurants) t
 WHERE t.rank<6;

-- FIND TOP 5 RESTAURANTS OF EVERY CUISINE AS PER THEIR REVENUE
SELECT * FROM
 (SELECT *,cost*rating_count AS "revenue",ROW_NUMBER() OVER(PARTITION BY cuisine ORDER BY cost*rating_count DESC) AS "rank" FROM restaurants) t
 WHERE t.rank<6;

